name: Build

on:
  push:
    branches:
    - main

jobs:
  html:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Get devTools/tweego from original repository
      run: |
        git clone -c core.symlinks=false --depth=1 https://gitgud.io/Vrelnir/degrees-of-lewdity.git _originalRepository
        cp -rf ./_originalRepository/devTools/tweego ./devTools/tweego
    - name: Run compile.sh
      run: |
        chmod +x ./compile.sh 
        FORCE_VERSION=kr-$(git describe --tags --always) ./compile.sh
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: dol-kr
    #     path: Degrees of Lewdity kr-*.html