name: Build

on:
  push:
    branches:
    - main

jobs:
  html:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get devTools/tweego from original repository
      run: |
        git clone -c core.symlinks=false --depth=1 https://gitgud.io/Vrelnir/degrees-of-lewdity.git _originalRepository
        cp -rf ./_originalRepository/devTools/tweego ./devTools/tweego
        cp -rf ./_originalRepository/img ./img

    - name: Run compile.sh
      run: |
        chmod +x ./compile.sh 
        FORCE_VERSION=kr-$(git describe --tags --always) ./compile.sh

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: dol-kr
    #     path: Degrees of Lewdity kr-*.html

  debug_apk:
    name: Build APK (Debug)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get devTools/tweego from original repository
      run: |
        git clone -c core.symlinks=false --depth=1 https://gitgud.io/Vrelnir/degrees-of-lewdity.git _originalRepository
        cp -rf ./_originalRepository/devTools/tweego ./devTools/tweego
        cp -rf ./_originalRepository/img ./img

    - name: Apply patch for APK build
      run: |
        sed -i 's/\"enableLinkNumberify\"\: true/\"enableLinkNumberify\"\: false/g' game/01-config/sugarcubeConfig.js
        chmod +x ./keys/initKeys.sh && ./keys/initKeys.sh

    - name: Run compile.sh
      run: |
        chmod +x ./compile.sh 
        FORCE_VERSION='' ./compile.sh

    - name: Build Cordova docker image
      run: |
        cd devTools/androidsdk/image
        docker build -t cordova-android:latest .

    - name: Build debug apk
      run: docker run -v "$GITHUB_WORKSPACE":"/src" -t cordova-android npm run build-debug

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: dol-kr-debug_apk
    #     path: dist/*-debug.apk

  release_apk:
    name: Build APK (Release)
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get devTools/tweego from original repository
      run: |
        git clone -c core.symlinks=false --depth=1 https://gitgud.io/Vrelnir/degrees-of-lewdity.git _originalRepository
        cp -rf ./_originalRepository/devTools/tweego ./devTools/tweego
        cp -rf ./_originalRepository/img ./img

    - name: Apply patch for APK build
      run: |
        sed -i 's/\"enableLinkNumberify\"\: true/\"enableLinkNumberify\"\: false/g' game/01-config/sugarcubeConfig.js
        chmod +x ./keys/initKeys.sh && ./keys/initKeys.sh

    - name: Run compile.sh
      run: |
        chmod +x ./compile.sh 
        FORCE_VERSION='' ./compile.sh

    - name: Build Cordova docker image
      run: |
        cd devTools/androidsdk/image
        docker build -t cordova-android:latest .

    - name: Build release apk
      run: docker run -v "$GITHUB_WORKSPACE":"/src" -t cordova-android npm run env -- cordova build --release

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: dol-kr-release-apk
    #     path: dist/*.apk
